### ISSUE TITLE
500/504 Errors

### ISSUE THREAD

**Issue by Arch881010** [nitheesh-cpu/hacapi#1]
Recieving 500 and 504 errors. Link has been provided, and thats when it gets caused.
Ignoring the link, throws incorrect username and password.

**Comment by nitheesh-cpu** [comment]
what link are you sending to the api?

**Comment by Arch881010** [comment]
Sorry for the late response.
But I am sending "https://hac20.esp.k12.ar.us/" as the query.

**Comment by Arch881010** [comment]
I believe this makes sense and may not be fixeable as the dropdown selects certain places. Let me know if thats the case.

**Comment by nitheesh-cpu** [comment]
is this website using powerschool, i believe it doesn’t have the same link structure

**Comment by Arch881010** [comment]
It is using powerschool. The way I login is (https://hac20.esp.k12.ar.us/HomeAccess20/Account/LogOn) and I don't think it follows as it requries a specific dropdown way of doing it. Which I checked it earlier.

**Comment by Arch881010** [comment]
Well, thank you at least.
